### ISSUE TITLE
implement: `endFriendship`

### ISSUE THREAD

**Issue by techjeffharris** [adminion/friends-of-friends#18]
**TODO**
- [ ] ~~in `lib/friendship.js` add static method `FriendshipSchema.statics.endFriendship(accoundId1, accountId2, done)` to end the friendship of two users~~
  1. ~~verify the users are friends~~
  2. ~~remove the friendship document~~
- [x] in `lib/plugin.js` add static method `schema.statics.endFriendship(accoundId1, accountId2, done)` which calls `Friendship.isAllowed()` 
- [x] in `lib/plugin.js` add instance method `schema.methods.endFriendship(accountId, done)` which calls `Friendship.isAllowed()` providing the document `_id` as the `accountId1`
