### ISSUE TITLE
deprecate: async FriendshipModel.methods.isRequest[er|ed]

### ISSUE THREAD

**Issue by techjeffharris** [adminion/friends-of-friends#44]
**TODO** 
- [ ] deprecate passing a callback
- [ ] warn on passing callback
- [ ] `return this._id.equals(accountId)` when no callback is provided
