### ISSUE TITLE
implement `isAllowed` to determine if a user may contact another account via a given access method

### ISSUE THREAD

**Issue by techjeffharris** [adminion/friends-of-friends#7]
**TODO**
- [ ] Privacy should be updated so that there is only one default privacy preference: 'Friend Request'.
- [ ] The user's privacy should then be an `Array` of `Object`s specifying the paths to be regulated and their privacy preference: `[{friendRequest: FriendsOfFriends.privacy.values.FRIENDS_OF_FRIENDS}, { 'profile': FriendsOfFriends.privacy.values.FRIENDS_OF_FRIENDS }]`
- [ ] Custom path preferences may be defined upon instantiation via the `regulatedPaths` property of the `options` object passed to the `FriendsOfFriends` constructor, or dynamically via `FriendsOfFriends.regulatePath('path')`.  
- [ ] Regulated paths may be viewed by `FriendsOfFriends.get('regulatedPaths')`
- [ ] Regulated paths may be removed with `FriendsOfFriends.deregulatePath('path')`.
- [ ] in `lib/friendship.js` add static method `FriendshipSchema.statics.isAllowed(accoundId1, accountId2, accessMethod, done)` to determine if a user may contact another account via a given access method
  1. determine relationship of users
  2. get requested user's privacy settings
  3.  determine if requester is allowed to contact requested via specified access method
- [ ] in `lib/plugin.js` add static method `schema.statics.isAllowed(accountId1, accountId2, accessMethod, done)` which calls `Friendship.isAllowed(...)` 
- [ ] in `lib/plugin.js` add instance method `schema.methods.isAllowed(accountId, accessMethod, done)` which calls `Friendship.isAllowed(...)` providing the document `_id` as the `accountId1`
